---
actions:
  to: kubernetes/app/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{artifactid}}
  name: {{artifactid}}
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{artifactid}}
  type: ClusterIP
status:
  loadBalancer: {}
